config/routes.rb
MongoOnRailsBlog::Application.routes.draw do
  devise_for :users
  resources :authors
  resources :articles do
    resources :comments
  end
  match "/articles/tag/:tag" => "articles#tag", :as => "articles_by_tag"
  match "/articles/author/:author" => "articles#author", :as => "articles_by_author"

  root :to => "articles#index"
end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :slug, :type => String
  field :title, :type => String
  field :body, :type => String
  field :published_at, :type => DateTime
  field :edited_at, :type => DateTime
  field :tags, :type => Array
  
  referenced_in :user, :stored_as => :array, :inverse_of => :articles
  embeds_many :comments

  key :slug

  before_save :set_edited_date
  before_create :set_slug,:set_published_date
  
  def set_published_date
    self.published_at = DateTime.now
  end
  
  def set_edited_date
    self.edited_at = DateTime.now
  end

  def set_slug
    self.slug = "#{title.parameterize}"
  end

  def self.tag_cloud
    map = <<EOF
      function() {
        for (index in this.tags) {
          emit(this.tags[index],1);
        }
      }
EOF
    reduce = <<EOF
      function(previous, current) {
        var count = 0;
        for (index in current) {
          count += current[index]
        }
        return count;
      }
EOF
    if Mongoid.master.collection(collection.name).count != 0
      collection.map_reduce(map,reduce).find()
    else
      []
    end
  end

  validates_presence_of :title, :body
  validates_uniqueness_of :slug

  index [[:published_date, Mongo::DESCENDING]]
  index :tags
  index :user

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :title, :type => String
  field :body, :type => String
  field :published_at, :type => DateTime

  embedded_in :article, :inverse_of => :comments
  referenced_in :user, :stored_as => :array, :inverse_of => :comment

  before_create :set_published_date

  def set_published_date
    self.published_at = DateTime.now
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable
  attr_accessible :name, :email, :password, :password_confirmation
  
  references_many :articles, :as => :array, :inverse_of => :user
  references_many :comments, :as => :array, :inverse_of => :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.paginate :page => params[:page], :per_page => 10, :sort => [[:published_at, :desc]]

    respond_to do |format|
      format.html
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    respond_to do |format|
      format.html
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    params[:article][:tags] = params[:article][:tags].split(',')
    @article = Article.new(params[:article])
    if user_signed_in?
      @article.user = current_user
    end
    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    params[:article][:tags] = params[:article][:tags].split(',')
    @article = Article.find(params[:id])
    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end

  # GET /articles/tag/1
  # GET /articles/tag/1.xml
  def tag
    @tag = params[:tag]
    @articles = Article.any_in(:tags => [@tag]).desc(:published_at)
    respond_to do |format|
      format.html
      format.xml  { render :xml => @articles }
    end
  end
  
  # GET /articles/author/1
  # GET /articles/author/1.xml
  def author
    @author = User.find(params[:author])
    @articles = @author.articles.desc(:published_at)
    respond_to do |format|
      format.html
      format.xml  { render :xml => @articles }
    end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # POST /comments
  # POST /comments.xml
  def create
    @article = Article.find(params[:article_id])
    if user_signed_in?
      params[:comment][:user] = current_user
    end
    @comment = @article.comments.create!(params[:comment])
    redirect_to @article, :notice => "Commented!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_article.html.haml
%h2.title= article.title
.body
  = article.body
-if article.tags
  %ul.tags
    - article.tags.each do |tag|
      %li
        = link_to tag, articles_by_tag_path(tag)
.infos
  = "#{article.published_at}"
  -if article.user
    By
    = link_to article.user.name, articles_by_author_path(article.user)
.clearfix
%ul.links
  %li= link_to 'Show', article
  - if article.user && current_user && current_user.id == article.user.id
    %li= link_to 'Edit', edit_article_path(article)
    %li= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete
.clearfix

app/views/articles/_form.html.haml
= semantic_form_for @article do |f|
  = f.inputs do
    = f.input :title
    = f.input :body, :as => :text
    - if @article.tags
      = f.input :tags, :input_html => {:value => @article.tags.join(',')}
    - else
      = f.input :tags
  = f.buttons do
    = f.commit_button

app/views/articles/author.html.haml
%h1= "Listing articles for user #{@author.name}"

- @articles.each do |article|
  %article
    = render :partial => 'articles/article', :object => article
    .clearfix

= link_to 'New Article', new_article_path

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 Listing articles

- @articles.each do |article|
  %article
    = render :partial => 'articles/article', :object => article
= will_paginate @articles
= link_to 'New Article', new_article_path

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%article
  = render :partial => 'articles/article', :object => @article

%h1 New Comment
= semantic_form_for [@article, Comment.new] do |f|
  = f.inputs do
    = f.input :title
    = f.input :body, :as => :text
  = f.buttons do
    = f.commit_button

app/views/articles/tag.html.haml
%h1= "Listing articles for tag #{@tag}"

- @articles.each do |article|
  %article
    = render :partial => 'articles/article', :object => article
    .clearfix

= link_to 'New Article', new_article_path

app/views/layouts/_header.html.haml
#userbar
  - if user_signed_in?
    %b Connected as
    = current_user.email
    %br
    = link_to "Sign Out", destroy_user_session_path
  - else
    = link_to "Sign In", new_user_session_path
    = link_to "Sign Up", new_user_registration_path

app/views/layouts/_right.html.haml
%ul.tagcloud
  - Article.tag_cloud.each do |tag|
    %li{:style => "font-size: #{tag['value']}em"}
      %a{:href => "#"}
        = link_to tag["_id"], articles_by_tag_path(tag["_id"])

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Blog
    = stylesheet_link_tag 'reset', 'scaffold', 'formtastic', 'style'
    = javascript_include_tag 'application', 'jquery.min', 'rails'
    = csrf_meta_tag
  %body
    %header
      = render :partial => 'layouts/header'
    %section.content
      %p#notice= notice
      %p#alert= alert
      = yield
    %section.right
      = render :partial => 'layouts/right'
    %footer